# Generated by Django 3.1.7 on 2021-09-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceyeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='place',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
