# Generated by Django 3.1.7 on 2021-09-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceyeapp', '0002_entry_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
