# Generated by Django 3.1.7 on 2021-09-25 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iceyeapp', '0003_lists'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lists',
            new_name='List_name',
        ),
        migrations.AlterModelOptions(
            name='list_name',
            options={'verbose_name_plural': 'Lists'},
        ),
    ]
