# Generated by Django 3.1.7 on 2021-09-26 00:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iceyeapp', '0006_remove_entry_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_name',
            name='text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
